site_name: Seguradora de imóveis
repo_url: https://github.com/guilherme-savio/seguro-imoveis

nav:
  - Home: index.md
  - Arquitetura de Solução: arquitetura.md
  - Modelo Relacional: relational.md
  - Camada Gold - One Big table: obt.md
  - ETL: etl.md
  - Autores: contributors.md

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - admonition


theme:
  name: material
  user_color_mode_toggle: true
  icon:
    logo: fontawesome/solid/house-lock
    favicon: fontawesome/solid/house-lock
  features:
  - content.code.copy


  palette:
  - scheme: default
    primary: light green
    toggle:
      icon: material/weather-night
      name: Modo Escuro

  - scheme: slate
    primary: light green
    toggle:
      icon: material/brightness-7
      name: Modo Claro
language: pt-BR